/*
 * seven_segment.c
 *
 *  Created on: Oct 11, 2022
 *      Author: mohammedhamdy32
 */

#include "seven_segment.h"
#include "common_macros.h"



#ifdef SEGMENT7_WITH_DECODER /*so I have a decoder*/
void SevenSegment_display(uint8 value)
{

	GPIO_setupPinDirection(SEGMENT7_PORT_ID, SEGMENT7_PIN0_ID, OUTPUT);
	GPIO_setupPinDirection(SEGMENT7_PORT_ID, SEGMENT7_PIN1_ID, OUTPUT);
	GPIO_setupPinDirection(SEGMENT7_PORT_ID, SEGMENT7_PIN2_ID, OUTPUT);
	GPIO_setupPinDirection(SEGMENT7_PORT_ID, SEGMENT7_PIN3_ID, OUTPUT);

	GPIO_writePin(SEGMENT7_PORT_ID, SEGMENT7_PIN0_ID , GET_BIT(value,0));
	GPIO_writePin(SEGMENT7_PORT_ID, SEGMENT7_PIN1_ID , GET_BIT(value,1));
	GPIO_writePin(SEGMENT7_PORT_ID, SEGMENT7_PIN2_ID , GET_BIT(value,2));
	GPIO_writePin(SEGMENT7_PORT_ID, SEGMENT7_PIN3_ID , GET_BIT(value,3));
}
#endif

#ifndef SEGMENT7_WITH_DECODER  /*so I don't have a decoder*/
void SevenSegment_display(uint8 value)
{
	GPIO_setupPortDirection(SEGMENT7_PORT_ID, 0xFF);
	switch(value)
	{
	case 0:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_LOW);
		break;
	case 1:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_LOW);
		break;
	case 2:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_HIGH);
		break;
	case 3:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_HIGH);
		break;
	case 4:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_HIGH);
		break;
	case 5:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_HIGH);
		break;
	case 6:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_HIGH);
		break;
	case 7:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_LOW);
		break;
	case 8:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_HIGH);
		break;
	case 9:
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN0_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN1_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN2_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN3_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN4_ID, LOGIC_LOW);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN5_ID, LOGIC_HIGH);
		GPIO_writePin(SEGMENT7_PORT_ID , SEGMENT7_PIN6_ID, LOGIC_HIGH);
		break;
	}

}
#endif
